// scripts/generate_reference.js — Consolidate reference source files into REFERENCE.md

var SOURCE_FILES = ["Language.md", "Types.md", "Math.md", "JSON.md"];
var REFERENCE_DIR = "reference";
var OUTPUT_FILE = "reference/REFERENCE.md";

function readMarkdownSection(path) {
  var fullPath = REFERENCE_DIR + "/" + path;
  var content = File.read(fullPath);
  var lines = content.split("\n");
  var title = path.replace(/\.md$/, "");
  var startIndex = 0;
  var index;
  var line;
  var bodyLines;
  var shifted;
  var result;

  index = 0;
  while (index < lines.length) {
    line = lines[index];
    if (/^# /.test(line)) {
      title = line.replace(/^# /, "").trim();
      if (!title) { title = path.replace(/\.md$/, ""); }
      startIndex = index + 1;
      break;
    }
    index = index + 1;
  }

  bodyLines = [];
  index = startIndex;
  while (index < lines.length) {
    bodyLines.push(lines[index]);
    index = index + 1;
  }

  while (bodyLines.length > 0 && !bodyLines[0]) {
    shifted = [];
    index = 1;
    while (index < bodyLines.length) {
      shifted.push(bodyLines[index]);
      index = index + 1;
    }
    bodyLines = shifted;
  }

  while (bodyLines.length > 0 && !bodyLines[bodyLines.length - 1]) {
    bodyLines.pop();
  }

  result = {};
  result["title"] = title;
  result["body"] = bodyLines;
  return result;
}

function shiftHeadingLevels(lines) {
  var shifted = [];
  var index = 0;
  var line;
  var match;
  var level;
  var newHashes;
  var j;

  while (index < lines.length) {
    line = lines[index];
    match = line.match(/^(#{1,6})(\s+.*)$/);
    if (!match || match === null) {
      shifted.push(line);
    } else {
      level = match[1].length + 1;
      if (level > 6) { level = 6; }
      newHashes = "";
      j = 0;
      while (j < level) {
        newHashes = newHashes + "#";
        j = j + 1;
      }
      shifted.push(newHashes + match[2]);
    }
    index = index + 1;
  }
  return shifted;
}

function appendSection(outputLines, file_name) {
  var section = readMarkdownSection(file_name);
  var shiftedLines;
  var j;

  outputLines.push("");
  outputLines.push("## " + section["title"]);
  outputLines.push("");

  shiftedLines = shiftHeadingLevels(section["body"]);
  j = 0;
  while (j < shiftedLines.length) {
    outputLines.push(shiftedLines[j]);
    j = j + 1;
  }
}

function buildOutput() {
  var outputLines = [];
  var i;
  var file_name;
  var label;

  outputLines.push("# GiavaScript JavaScript Feature Reference");
  outputLines.push("");
  outputLines.push("This file is auto-generated by `scripts/generate_reference.js`.");
  outputLines.push("");
  outputLines.push("## Table of Contents");
  outputLines.push("");
  outputLines.push("- [Consolidated Reference](REFERENCE.md)");

  i = 0;
  while (i < SOURCE_FILES.length) {
    file_name = SOURCE_FILES[i];
    label = file_name.replace(/\.md$/, "");
    outputLines.push("- [" + label + "](" + file_name + ")");
    i = i + 1;
  }

  outputLines.push("");
  outputLines.push("Regenerate this file with:");
  outputLines.push("");
  outputLines.push("```bash");
  outputLines.push("crystal run src/giavascript_cli.cr -- scripts/generate_reference.js");
  outputLines.push("```");
  outputLines.push("");
  outputLines.push("Source files:");

  i = 0;
  while (i < SOURCE_FILES.length) {
    outputLines.push("- `reference/" + SOURCE_FILES[i] + "`");
    i = i + 1;
  }

  i = 0;
  while (i < SOURCE_FILES.length) {
    appendSection(outputLines, SOURCE_FILES[i]);
    i = i + 1;
  }

  outputLines.push("");
  return outputLines.join("\n");
}

function main() {
  File.write(OUTPUT_FILE, buildOutput());
}

main();
