#!/usr/bin/env python3

from __future__ import annotations

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parent.parent
REFERENCE_DIR = ROOT / "reference"
OUTPUT_FILE = REFERENCE_DIR / "REFERENCE.md"
SOURCE_FILES = [
    "Language.md",
    "Types.md",
    "Math.md",
    "JSON.md",
]


def read_markdown_section(path: Path) -> tuple[str, list[str]]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines:
        return path.stem, []

    title = path.stem
    start_index = 0
    for index, line in enumerate(lines):
        if line.startswith("# "):
            title = line[2:].strip() or path.stem
            start_index = index + 1
            break

    body = lines[start_index:]
    while body and body[0].strip() == "":
        body.pop(0)

    return title, body


def build_output() -> str:
    output_lines: list[str] = [
        "# GiavaScript JavaScript Feature Reference",
        "",
        "This file is auto-generated by `scripts/generate_reference.py`.",
        "",
        "Source files:",
    ]

    for file_name in SOURCE_FILES:
        output_lines.append(f"- `reference/{file_name}`")

    for file_name in SOURCE_FILES:
        source_path = REFERENCE_DIR / file_name
        if not source_path.exists():
            raise FileNotFoundError(f"Missing source file: {source_path}")

        title, body = read_markdown_section(source_path)
        output_lines.extend(["", f"## {title}", ""])

        if body:
            output_lines.extend(shift_heading_levels(body))
        else:
            output_lines.append("No content yet.")

    output_lines.append("")
    return "\n".join(output_lines)


def shift_heading_levels(lines: list[str]) -> list[str]:
    shifted: list[str] = []
    for line in lines:
        match = re.match(r"^(#{1,6})(\s+.*)$", line)
        if not match:
            shifted.append(line)
            continue

        hashes, rest = match.groups()
        shifted_level = min(6, len(hashes) + 1)
        shifted.append(f"{'#' * shifted_level}{rest}")

    return shifted


def main() -> None:
    OUTPUT_FILE.write_text(build_output(), encoding="utf-8")
    print(f"Updated {OUTPUT_FILE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
